spring.application.name=ride-management-service
server.port=8083

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ride_mgmt_db}
app.security.jwt-secret=${JWT_SECRET:}
app.services.driver-vehicle.base-url=${DRIVER_VEHICLE_SERVICE_URL:http://localhost:8082}
app.services.fare-payment.base-url=${FARE_PAYMENT_SERVICE_URL:http://localhost:8084}
spring.rabbitmq.addresses=${CLOUDAMQP_URL:amqp://localhost:5672}
