spring.application.name=fare-payment-service
server.port=8084

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/fare_payment_db}
app.security.jwt-secret=${JWT_SECRET:}
spring.rabbitmq.addresses=${CLOUDAMQP_URL:amqp://localhost:5672}
